# Generated by Django 2.2 on 2019-05-12 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_team_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own', models.BooleanField(default=False)),
                ('allocation', models.PositiveSmallIntegerField(default=33, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('month', models.CharField(choices=[('PP', 'Proposal'), ('ID', 'Interface'), ('DD', 'Database'), ('IF', 'Functionality'), ('FS', 'Final')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='ratings',
            field=models.ManyToManyField(to='main.Rating'),
        ),
    ]
