# Generated by Django 2.2 on 2019-05-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190512_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='month',
            new_name='phase',
        ),
    ]
