# Generated by Django 2.2 on 2019-05-13 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190513_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ratings',
        ),
        migrations.AddField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
            preserve_default=False,
        ),
    ]
