# Generated by Django 2.2 on 2019-05-13 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_student_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
            preserve_default=False,
        ),
    ]
