# Generated by Django 2.2 on 2019-05-13 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rating_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'get_latest_by': ['created_at', 'updated_at']},
        ),
        migrations.AddField(
            model_name='rating',
            name='allocator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='allocator', to='main.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='main.Student'),
        ),
    ]
