# Generated by Django 2.2 on 2019-05-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190513_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_no',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True),
        ),
    ]
