# Generated by Django 2.2 on 2019-05-17 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190513_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_letter', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True, verbose_name='Team')),
                ('class_no', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='team_letter',
        ),
        migrations.AlterField(
            model_name='student',
            name='class_no',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddConstraint(
            model_name='classteam',
            constraint=models.UniqueConstraint(fields=('team_letter', 'class_no'), name='unique_team'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.ClassTeam'),
            preserve_default=False,
        ),
    ]
