# Generated by Django 2.2 on 2019-05-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190517_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='use',
            field=models.BooleanField(default=True),
        ),
    ]
