# Generated by Django 2.2 on 2019-05-19 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rating_use'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classteam',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
