# Generated by Django 2.2 on 2019-05-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_rating_own'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'get_latest_by': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='updated_at',
        ),
    ]
