# Generated by Django 2.2 on 2019-05-19 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190519_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classno',
            name='class_no',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='classteam',
            name='class_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ClassNo'),
        ),
    ]
