# Generated by Django 2.2 on 2019-05-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_classteam_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classteam',
            name='limit',
        ),
    ]
