# Generated by Django 2.2 on 2019-05-28 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_classteam_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteam',
            name='limit',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(30)]),
        ),
    ]
